const data = {
    products: [
        {
            name: 'Free Shirt',
            slug: 'free-shirt',
            category: 'Shirts',
            image: '/images/shirt1.jpg',
            price: 70,
            brand: 'Momus',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'Popular shirt among comedians',
        },
        {
            name: 'Press Shirt',
            slug: 'press-shirt',
            category: 'Shirts',
            image: '/images/shirt2.jpg',
            price: 80,
            brand: 'Thanatos',
            rating: 4.2,
            numReviews: 10,
            countInStock: 20,
            description: 'Popular shirt among geeks',
        },
        {
            name: 'Fit Shirt',
            slug: 'fit-shirt',
            category: 'Shirts',
            image: '/images/shirt3.jpg',
            price: 80,
            brand: 'Thanatos',
            rating: 4.2,
            numReviews: 10,
            countInStock: 20,
            description: 'Popular shirt among coders',
        },
        {
            name: 'Golf Pants',
            slug: 'golf-pants',
            category: 'Pants',
            image: '/images/pants1.jpg',
            price: 90,
            brand: 'Typhon',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'Popular pants among golfers',
        },
        {
            name: 'Fit Pants',
            slug: 'fit-pants',
            category: 'Pants',
            image: '/images/pants2.jpg',
            price: 95,
            brand: 'Hera',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'Popular pants among esports',
        },
        {
            name: 'Jogger Pants',
            slug: 'jogger-pants',
            category: 'Pants',
            image: '/images/pants3.jpg',
            price: 100,
            brand: 'Apollo',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'Popular pants among coders',
        },
    ],
}

export default data;
